### ISSUE TITLE
Are you going to continue this project?

### ISSUE THREAD

**Issue by FJLopezGarcia** [FabienDehopre/my-netatmo-dashboard#1]
HI @FabienDehopre Thanks a lot for sharing your repo in Github!! 
I would like to do the same but collecting metrics from a Netatmo termostat and I would like to see how do you continue your development and take a look at the way you get metrics from netatmo service: https://api.netatmo.com/api/getmeasure?access_token=<token>&device_id=<deviceid>&module_id=<module_id>........

It will help me a lot!!

Regards
Javi

**Comment by FabienDehopre** [comment]
Hi @FJLopezGarcia I was busy with my daily work. I just pushed a new commit in which I created a cloud function that updates all all the users data (access token, stations, devices, and dashboard data). I plan to call that function on schedule (+/- 15 minutes).

**Comment by FabienDehopre** [comment]
I also found that I cannot access the netatmo api from cloud functions. I have to investigate.

**Comment by FabienDehopre** [comment]
I just found why I cannot access netatmo api from cloud functions. It's because I'm on the free plan that only allows external call to google apis.
So since I'm not willing to pay anything for this projet, I think I will develop this using .NET Core for the backend

**Comment by FJLopezGarcia** [comment]
It makes sense!! Thanks for sharing your findings and code... i bought a netatmo weather station yesterday night.. lot of time thinking to do it!! Now waiting for the delivery and desiring to test your code :-) thanks a lot and please go ahead with this project, learning a lot!

**Comment by FJLopezGarcia** [comment]
How is going my friend!! I suppose busy with your daily work... waiting for new updates !! :-) thx
