### ISSUE TITLE
Not getting the stations

### ISSUE THREAD

**Issue by FJLopezGarcia** [FabienDehopre/my-netatmo-dashboard#2]
Do you know the reason why i am not getting the stations in the dropdown? Thanks a lot!!

![image](https://user-images.githubusercontent.com/6631983/48445427-d76aa000-e796-11e8-8632-567d80015b3b.png)

**Comment by FabienDehopre** [comment]
No really. Except if the stations are not present in the firestore.
Do you see the stations in your firestore collection (under /users/{userId}/stations) ?
Otherwise, I'm not an expert in Firebase development. I use this project to learn it.

**Comment by FJLopezGarcia** [comment]
No i cannot see them :-( 
![image](https://user-images.githubusercontent.com/6631983/48577076-871a4c00-e916-11e8-86b9-3ec00dbf6f57.png)
